[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "wezterm start --class main-dropterm"
class = "main-dropterm"
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.explore]
animation = "fromBottom"
command = "wezterm start --class floating-term -- yazi"
class = "floating-term"
size = "75% 75%"
max_size = "1920px 100%"
